deployCode/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Total cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/objects/Schedule__c.object
<CustomObject>
    <description>Time Table</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_days__c</fullName>
        <label>No of days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_nights__c</fullName>
        <label>No of nights</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Total cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/classes/Booking.cls
public class Booking {
    
  private ApexPages.StandardController booking;
    public id pdfbookid{set; get;}
     public string reportId{set; get;}
   public Booking__c book{Set;get;}
    public contact con{get;set;}
    public Schedule__c sch{get;set;}
    
  public Booking(ApexPages.StandardController controllerParam){
      booking = controllerParam;
		book= new Booking__C();
        book= [select name, customer__c,Schedule__c from booking__C where name =:  booking.getId() ];
             con= [select Id,name,firstname,lastname,email,birthdate,accountid,mobilephone  from contact where id =: book.Customer__c];
      sch= [select Total_cost__c,No_of_days__c,No_of_nights__c from Schedule__C where id =: book.Schedule__c ];
       System.debug(booking.getId());
       System.debug(book);
       System.debug(con.Email);
  }
   
}