deployCode/objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Total cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tour_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Package</label>
        <referenceTo>Tour_Packages__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Tour_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Package</label>
        <referenceTo>Tour_Packages__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

deployCode/objects/Offer__c.object
<CustomObject>
    <description>Offer details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/objects/Schedule__c.object
<CustomObject>
    <description>Time Table</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_of_days__c</fullName>
        <label>No of days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_nights__c</fullName>
        <label>No of nights</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_cost__c</fullName>
        <label>Total cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tour_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Package</label>
        <referenceTo>Tour_Packages__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/objects/Tour_Packages__c.object
<CustomObject>
    <description>Tells about the package details</description>
    <fields>
        <fullName>Cost_per_day__c</fullName>
        <label>Cost_per_day</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Tour Packages</relationshipLabel>
        <relationshipName>Tour_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour Package</label>
    <nameField>
        <label>Tour Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/classes/TourManage.cls
public class TourManage{
    
    public Schedule__c sd {set; get;}
    public Contact contact{set; get;}
    public Booking__c book{set;get;}    
    public Schedule__c schedule{set;get;}
	public String selectedRowIndex	{get;set;} 
    public Tour_Packages__c tpc{get;set;} 
    public Offer__c off{get;set;} 
	public Integer count = 0;
    public Decimal dis = 0;
    public Integer costcount=0;
    Public Decimal totalcost=0;
   	public Date datename {get; set;}
  
    public String strText {get;set;}
    public Tour_Packages__c tour1{set;get;}
    
	public TourManage(){
		 contact=new contact();
        schedule = new Schedule__c();
        tour1=new Tour_Packages__c();
        schedule.Total_Cost__c=0;
        book = new Booking__c();    
        strText = ApexPages.currentPage().getParameters().get('name');
        tour1=[select id,name,cost_per_day__c from Tour_Packages__c where name=: strText];
        contact.Tour_Package__c=tour1.Id;
        system.debug(strText);
    }
     
    public PageReference BookAnother(){
        
        PageReference pr = new PageReference('/apex/Googlemap');
        return pr;
        
    }
    
    public PageReference Save()	{
        
        
       try{
         upsert contact;       
        system.debug('savecontact');
        
        schedule.Tour_Package__c=tour1.Id;
        schedule.Customer__c=contact.Id;
        //tpc=[select Cost_per_day__c,id from Tour_Packages__c where id =: tour1.Name ];
        system.debug('beforeschedule');
         upsert schedule;
        system.debug('afterschedule');
        book.Customer__c= contact.id;
       	book.Schedule__c=schedule.id;
        book.Tour_Package__c=tour1.Id;
        book.Total_cost__c=schedule.Total_Cost__c; 
        upsert book;
           PageReference pr = new PageReference('/apex/BookingConfirmed');		
		return pr;
           }catch(Exception e){
            system.debug('schedulecatch');
            Apexpages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.FATAL, e.getMessage()));
               return null;
        }
       // System.debug(book.Customer__c+' '+contact.id);
        //System.debug(book.Schedule__c+''+schedule.id);
        //System.debug(book.Tour_Package__c+''+schedule.Tour_Package__c);
        //System.debug(book.Total_cost__c+''+schedule.Total_Cost__c);       
       
        //pr.setRedirect(True);
		
	}
    public void fetchCostDetails(){
        tpc = [SELECT id,Cost_per_Day__c FROM Tour_Packages__c WHERE Id =:  contact.Tour_Package__c];
        schedule.Total_Cost__c =schedule.Total_Cost__c+ tpc.Cost_per_Day__c*noOfWorkingdaysDiff;
        System.debug('hi');
      
       
         
    }
    public void OfferDetails(){
        if(contact.AccountId!=null){
        off=[select id, Discount__c from Offer__c where Account__c =: contact.AccountId];
        dis=off.Discount__c;
        costcount=0;
        system.debug('discount'+dis);
        schedule.Offer__c= off.Id;
        FinalCost();    
        }
        System.debug(off);           
    }
    public void FinalCost(){
        
        if(costcount==0){
        schedule.Total_Cost__c =  totalcost - (totalcost*dis)/100;
            costcount=1;
        }
            
            
        System.debug(off);           
    }
    public Integer noOfWorkingdaysDiff{set;get;}
    public void DayCaculate(){
        System.debug('daycalculate');
        noOfWorkingdaysDiff=schedule.From__c.daysBetween(schedule.To__c);
        if( noOfWorkingdaysDiff>0){
		schedule.No_of_Days__c= noOfWorkingdaysDiff;    
        schedule.No_of_Nights__c= noOfWorkingdaysDiff; 
        tpc = [SELECT id,Cost_per_Day__c FROM Tour_Packages__c WHERE name =:  tour1.Name];
        
        schedule.Total_Cost__c =tpc.Cost_per_Day__c*noOfWorkingdaysDiff;
        totalcost=Schedule.Total_cost__c;
        System.debug('hi'+totalcost);
        costcount=0;
        }
    }
        
    public PageReference viewplaces(){
    
    PageReference pr = new PageReference('/apex/googlemap');		
		return pr;
    }
    
}