deployCode/objects/Places__c.object
<CustomObject>
    <description>Location info</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Place</label>
    <nameField>
        <label>Places Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Places</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deployCode/classes/lightningMapController.cls
public with sharing class lightningMapController {
    
    @AuraEnabled public static string country{get;set;} 
    @AuraEnabled
    public Static void setcountry(String mycountry) {
       
       country=mycountry;
         System.debug(''+country);
    }
    @AuraEnabled
    public Static String getCountry() {
        System.debug(country);
        return country;
    }
    @AuraEnabled
    public static list<accountLocationWrapper> getLocation(){
        list<accountLocationWrapper> lstALW = new list<accountLocationWrapper>();
        /*Query accounts records with billing address information */  
        List<places__c> mapplace;
        if(country==null || country==''){
            mapplace=[select id, name, country__c, city__c, rating__c,State__c from places__c 
                           Where country__c != null
                           And city__c != null 
                           limit 3];
            System.Debug('Empty'+mapplace);
        }
        else{ 
               mapplace=[ select id, name, country__c, city__c, rating__c,State__c from places__c 
                           Where country__c =: country
                           And city__c != null  
                           limit 3];
            System.Debug('Filled'+mapplace);
        }
            
        for(places__c acc :mapplace){
                               // first create "locationDetailWrapper" instance and set appropriate values
                               locationDetailWrapper oLocationWrap = new locationDetailWrapper();
                              // oLocationWrap.Street = acc.BillingStreet;
                              // oLocationWrap.PostalCode = acc.BillingPostalCode;
                               oLocationWrap.City = acc.city__c;
                               oLocationWrap.State = acc.State__c;
                               oLocationWrap.Country = acc.country__c;
                               
                               // create "accountLocationWrapper" instance, set values and add to final list. 
                               accountLocationWrapper oWrapper = new accountLocationWrapper();
                               oWrapper.icon = 'utility:location'; // https://www.lightningdesignsystem.com/icons/#utility
                               oWrapper.title = acc.Name;
                          //     oWrapper.description = acc.description;
                               oWrapper.location = oLocationWrap;
                               
                               lstALW.add(oWrapper);
                           }
        // retrun the "accountLocationWrapper" list
        return lstALW;
    }
    /* wrapper class to store required properties for "lightning:map" component' */ 
    public class accountLocationWrapper{
        @AuraEnabled public string icon{get;set;} 
        @AuraEnabled public string title{get;set;} 
        @AuraEnabled public string description{get;set;} 
        @AuraEnabled public locationDetailWrapper location{get;set;} 
    }
    /* sub wrapper class to store location details for "accountLocationWrapper" location property.*/ 
    public class locationDetailWrapper{
        @AuraEnabled public string Street{get;set;}
        @AuraEnabled public string PostalCode{get;set;}
        @AuraEnabled public string City{get;set;}
        @AuraEnabled public string State{get;set;}
        @AuraEnabled public string Country{get;set;}
    }
    
    
}